version: '3.9'

services:
  db:
    image: postgres:12.4
    container_name: pg_db
    restart: always
    volumes:
      - ./logs:/var/log
    env_file:
      - ./.env

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    depends_on:
      - db

  app:
    build: .
    image: netology_pd_diplom:latest
    container_name: app
    depends_on:
      - redis
    restart: always
    env_file:
      - ./.env
    volumes:
    - .:/app
    - static_volume:/app/static
    - media_volume:/app/media
    entrypoint: /app/entrypoint.sh

  nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./nginx/
    container_name: app_nginx
    image: app_nginx
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - app
    restart: always

volumes:
  static_volume:
  media_volume:
