version: '3.9'

services:

  pg_db:
    image: postgres:14.3-alpine3.15
    container_name: pg_db
    ports:
      - "5431:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: dp_base
    volumes:
      - ./logs:/var/log

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    depends_on:
      - pg_db

  app:
    build: .
    image: netology_pd_diplom:latest
    container_name: app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    command: [sh, -c, "celery -A netology_pd_diplom worker -D  &&
    python manage.py collectstatic --noinput &&
    python manage.py migrate && gunicorn netology_pd_diplom.wsgi:application -b 0.0.0.0:8000"]

  nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./docker/nginx/
    container_name: app_nginx
    image: app_nginx
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - app
    ports:
      - "${NGINX_EXTERNAL_PORT}:80"

volumes:
  static_volume:
  media_volume: